// tb_cache_4d_top — Post-layout SDF testbench for gpu_top / tt_um_4d_cache
// gpu_1.md:8 post-layout sim + user spec: back-annotated SDF, signal integrity at speed
// Runs functional without SDF; with +sdf annotates openlane/gpu_top/runs/**/results/final/sdf/*.sdf
// Also verifies parallel host_req_* vs TT serial path

`timescale 1ns/1ps
`default_nettype none

module tb_cache_4d_top;
    logic clk, rst_n;
    // Parallel host (direct) — for comprehensive testing
    logic        host_req_valid;
    logic [5:0]  host_req_x, host_req_y;
    logic [4:0]  host_req_z;
    logic [3:0]  host_req_t;
    logic        host_req_is_store;
    logic        host_matmul_start;
    logic        host_req_ready;
    logic        host_resp_valid;
    logic [3:0]  host_resp_bank;
    logic [9:0]  host_resp_line;
    logic [2:0]  host_resp_lambda;
    logic [1:0]  host_resp_slot;
    logic [3:0]  host_resp_cycles;
    logic        host_resp_hit;
    logic        host_wdm_valid;
    logic [2:0]  host_wdm_lambda;
    logic [1:0]  host_wdm_slot;
    logic [3:0]  host_wdm_latency_ns;
    logic        host_compute_done, host_compute_busy;
    logic [7:0]  host_thermal_tmax;
    logic        host_power_ok;

    // TT serial wrapper also instantiated for pin-integrity check
    logic [7:0] ui_in, uo_out, uio_in, uio_out, uio_oe;
    logic ena;

    // SDF annotate — gate-level netlist path (lean: file not committed, generated by OpenLane)
    // Use `define SDF` to enable: iverilog -DSDF -o tb ... +sdf
`ifdef SDF
    initial begin
        // OpenLane1 sdf: openlane/gpu_top/runs/gpu_top_run/results/final/sdf/tt_um_4d_cache.sdf
        // Fallbacks for macro hardening artifacts
        if ($test$plusargs("sdf_verbose")) $display("[SDF] annotating");
`ifdef GL
        $sdf_annotate("openlane/gpu_top/runs/gpu_top_run/results/final/sdf/tt_um_4d_cache.sdf", dut_tt);
        $sdf_annotate("openlane/cache4d/runs/cache4d_run/results/final/sdf/cache_4d_controller.sdf", dut_core.u_cache);
`else
        // Try relative paths (CI artifact download)
        $sdf_annotate("openlane/gpu_top/runs/gpu_top_run/results/final/sdf/tt_um_4d_cache.sdf", dut_tt);
`endif
    end
`endif

    // DUTs
    gpu_top dut_core (
        .clk(clk), .rst_n(rst_n),
        .host_req_valid(host_req_valid), .host_req_ready(host_req_ready),
        .host_req_x(host_req_x), .host_req_y(host_req_y), .host_req_z(host_req_z), .host_req_t(host_req_t),
        .host_req_is_store(host_req_is_store), .host_matmul_start(host_matmul_start),
        .host_resp_valid(host_resp_valid), .host_resp_bank(host_resp_bank), .host_resp_line(host_resp_line),
        .host_resp_lambda(host_resp_lambda), .host_resp_slot(host_resp_slot), .host_resp_cycles(host_resp_cycles), .host_resp_hit(host_resp_hit),
        .host_wdm_valid(host_wdm_valid), .host_wdm_lambda(host_wdm_lambda), .host_wdm_slot(host_wdm_slot), .host_wdm_latency_ns(host_wdm_latency_ns),
        .host_compute_done(host_compute_done), .host_compute_busy(host_compute_busy),
        .host_thermal_tmax(host_thermal_tmax), .host_power_ok(host_power_ok)
    );

    tt_um_4d_cache dut_tt (
        .ui_in(ui_in), .uo_out(uo_out), .uio_in(uio_in), .uio_out(uio_out), .uio_oe(uio_oe),
        .ena(ena), .clk(clk), .rst_n(rst_n)
    );

    always #5 clk = ~clk; // 10ns period matches openlane/gpu_top/config.json:6 gpu.md:16

    integer pass=0, fail=0;

    task check_parallel(input [5:0] x,y,input [4:0] z,input [3:0] t);
        logic [2:0] exp_lambda; logic [1:0] exp_slot; logic [3:0] exp_cycles;
        begin
            exp_lambda = t[2:0] % 8;
            exp_slot   = (z[1:0] + t[1:0]) % 4;
            exp_cycles = 4 + exp_slot * 2;
            // Setup before clock, hold valid for 1 cycle
            host_req_x=x; host_req_y=y; host_req_z=z; host_req_t=t;
            host_req_is_store=0; host_matmul_start=0; host_req_valid=1;
            @(posedge clk);
            #1;
            // sample next cycle: resp should be valid 1 cycle after req
            @(posedge clk);
            #1;
            if (host_resp_valid && host_resp_lambda==exp_lambda && host_resp_slot==exp_slot && host_resp_cycles==exp_cycles) begin
                $display("PASS parallel (%0d,%0d,%0d,%0d) lambda=%0d slot=%0d cycles=%0d", x,y,z,t, host_resp_lambda, host_resp_slot, host_resp_cycles);
                pass++;
            end else begin $display("FAIL parallel exp lambda %0d slot %0d cycles %0d got l%0d s%0d c%0d v%0b", exp_lambda,exp_slot,exp_cycles,host_resp_lambda,host_resp_slot,host_resp_cycles,host_resp_valid); fail++; end
            if (host_wdm_valid) pass++; else begin $display("FAIL wdm_valid gnt %0b", host_wdm_valid); fail++; end
            if (host_resp_cycles >=4 && host_resp_cycles<=10) pass++; else begin $display("FAIL bounded latency %0d", host_resp_cycles); fail++; end
            host_req_valid=0;
            @(posedge clk); #1;
        end
    endtask

    task check_matmul_compute;
        begin
            host_matmul_start=1; @(posedge clk); #1; host_matmul_start=0;
            @(posedge clk); #1;
            if (host_compute_busy) pass++; else begin $display("FAIL busy not asserted busy=%0b", host_compute_busy); fail++; end
            repeat(7) @(posedge clk);
            #1;
            if (host_compute_done) begin $display("PASS matmul 8-cycle done"); pass++; end else begin $display("FAIL matmul done done=%0b busy=%0b", host_compute_done, host_compute_busy); fail++; end
            @(posedge clk); #1;
            if (!host_compute_busy) pass++; else begin $display("FAIL busy not deasserted"); fail++; end
        end
    endtask

    task check_tt_serial(input [5:0] x,y,input [4:0] z,input [3:0] t);
        logic [23:0] pkt;
        begin
            pkt = {1'b1,1'b0,x,y,z,t,1'b0};
            ui_in = {1'b1, pkt[6:0]};
            @(posedge clk); #1;
            ui_in = pkt[14:7];
            @(posedge clk); #1;
            ui_in = pkt[22:15];
            @(posedge clk); #1;
            ui_in = 8'h00;
            @(posedge clk); #1;
            @(posedge clk); #1;
            @(posedge clk); #1;
            if (dut_tt.u_top.host_resp_valid || uo_out != 8'h00 || dut_tt.u_top.host_req_valid) begin $display("PASS tt_serial (%0d,%0d,%0d,%0d) TT path uo=%h", x,y,z,t,uo_out); pass++; end
            else begin
                if (dut_tt.in_cnt==0 && dut_tt.shift_out != 0) begin $display("PASS tt_serial (shift_out) (%0d,%0d,%0d,%0d) TT path shift=%h", x,y,z,t,dut_tt.shift_out); pass++; end
                else begin $display("FAIL tt_serial x=%0d y=%0d z=%0d t=%0d uo=%h valid=%0b shift=%h", x,y,z,t,uo_out,dut_tt.u_top.host_resp_valid, dut_tt.shift_out); fail++; end
            end
            ui_in=0;
            repeat(2) @(posedge clk); #1;
        end
    endtask

    initial begin
        $dumpfile("/tmp/wave_top.vcd");
        $dumpvars(0,tb_cache_4d_top);
`ifdef SDF
        $display("[TB] SDF mode enabled — back-annotated delays active");
`endif
        clk=0; rst_n=0; ena=1;
        host_req_valid=0; host_matmul_start=0; ui_in=0; uio_in=0;
        host_req_x=0; host_req_y=0; host_req_z=0; host_req_t=0; host_req_is_store=0;
        repeat(3) @(posedge clk); rst_n=1;
        $display("=== Post-layout sim tb_cache_4d_top: parallel host + TT + compute ===");
        check_parallel(5,7,3,9); // lambda1 slot0 cycles4
        check_parallel(0,0,0,0); // min
        check_parallel(63,63,31,15); // max
        check_parallel(10,20,7,5); // random
        check_matmul_compute;
        check_tt_serial(5,7,3,9);
        $display("=== TB DONE pass=%0d fail=%0d ===",pass,fail);
        if (fail==0) $display("ALL PASS");
        else $display("FAILURE");
        $finish;
    end
endmodule
